-- UGAFORCE-HR Group 1: centralized workflow + analytics
CREATE TABLE IF NOT EXISTS ugaforce_hr_workflow_definitions(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),name TEXT NOT NULL,resource_type TEXT NOT NULL,is_active BOOLEAN NOT NULL DEFAULT true,sla_hours INTEGER NOT NULL DEFAULT 48,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ugaforce_hr_workflow_steps(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),workflow_id UUID NOT NULL REFERENCES ugaforce_hr_workflow_definitions(id) ON DELETE CASCADE,step_order INTEGER NOT NULL,approver_role TEXT NOT NULL,required_approvals INTEGER NOT NULL DEFAULT 1,UNIQUE(workflow_id,step_order));
CREATE TABLE IF NOT EXISTS ugaforce_hr_approval_requests(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),workflow_id UUID REFERENCES ugaforce_hr_workflow_definitions(id),resource_type TEXT NOT NULL,resource_id UUID NOT NULL,requested_by UUID REFERENCES ugaforce_hr_employees(id),current_step INTEGER NOT NULL DEFAULT 1,status TEXT NOT NULL DEFAULT 'pending',due_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),completed_at TIMESTAMPTZ);
CREATE INDEX IF NOT EXISTS idx_hr_approval_inbox ON ugaforce_hr_approval_requests(status,due_at);
CREATE TABLE IF NOT EXISTS ugaforce_hr_approval_actions(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),request_id UUID NOT NULL REFERENCES ugaforce_hr_approval_requests(id) ON DELETE CASCADE,step_order INTEGER NOT NULL,actor_id UUID REFERENCES ugaforce_hr_employees(id),action TEXT NOT NULL,comments TEXT,acted_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ugaforce_hr_approval_delegations(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),delegator_id UUID NOT NULL REFERENCES ugaforce_hr_employees(id),delegate_id UUID NOT NULL REFERENCES ugaforce_hr_employees(id),starts_at TIMESTAMPTZ NOT NULL,ends_at TIMESTAMPTZ NOT NULL,is_active BOOLEAN NOT NULL DEFAULT true,CHECK(ends_at>starts_at));
CREATE TABLE IF NOT EXISTS ugaforce_hr_analytics_snapshots(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),metric_date DATE NOT NULL DEFAULT CURRENT_DATE,metric_key TEXT NOT NULL,metric_value NUMERIC(18,4) NOT NULL,dimensions JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_hr_analytics_metric ON ugaforce_hr_analytics_snapshots(metric_key,metric_date DESC);
INSERT INTO ugaforce_hr_role_permissions(role_id,resource,can_view,can_edit,scope) SELECT r.id,x.resource,x.v,x.e,x.s FROM ugaforce_hr_roles r JOIN (VALUES ('MANAGER','approvals',true,true,'team'),('HR_SPECIALIST','approvals',true,true,'all'),('HR_MANAGER','approvals',true,true,'all'),('HR_ADMIN','approvals',true,true,'all'),('HR_SPECIALIST','analytics',true,false,'all'),('HR_MANAGER','analytics',true,false,'all'),('HR_ADMIN','analytics',true,true,'all')) x(role_name,resource,v,e,s) ON r.name=x.role_name ON CONFLICT(role_id,resource) DO UPDATE SET can_view=excluded.can_view,can_edit=excluded.can_edit,scope=excluded.scope;