-- UGAFORCE-HR Group 2 completion: notifications, communications, offboarding and security controls
CREATE TABLE IF NOT EXISTS ugaforce_hr_notifications(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),employee_id UUID REFERENCES ugaforce_hr_employees(id) ON DELETE CASCADE,channel TEXT NOT NULL DEFAULT 'in_app',subject TEXT NOT NULL,body TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'queued',created_at TIMESTAMPTZ NOT NULL DEFAULT now(),sent_at TIMESTAMPTZ,read_at TIMESTAMPTZ);
CREATE INDEX IF NOT EXISTS idx_hr_notifications_employee ON ugaforce_hr_notifications(employee_id,status,created_at DESC);
CREATE TABLE IF NOT EXISTS ugaforce_hr_offboarding_cases(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),employee_id UUID NOT NULL REFERENCES ugaforce_hr_employees(id),last_working_date DATE NOT NULL,reason TEXT,status TEXT NOT NULL DEFAULT 'in_progress',started_by UUID REFERENCES ugaforce_hr_employees(id),started_at TIMESTAMPTZ NOT NULL DEFAULT now(),completed_at TIMESTAMPTZ,UNIQUE(employee_id,status));
CREATE TABLE IF NOT EXISTS ugaforce_hr_offboarding_tasks(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),case_id UUID NOT NULL REFERENCES ugaforce_hr_offboarding_cases(id) ON DELETE CASCADE,title TEXT NOT NULL,owner_role TEXT,status TEXT NOT NULL DEFAULT 'pending',due_date DATE,completed_at TIMESTAMPTZ,notes TEXT);
CREATE INDEX IF NOT EXISTS idx_hr_offboarding_tasks ON ugaforce_hr_offboarding_tasks(case_id,status,due_date);
CREATE TABLE IF NOT EXISTS ugaforce_hr_exit_interviews(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),case_id UUID NOT NULL UNIQUE REFERENCES ugaforce_hr_offboarding_cases(id) ON DELETE CASCADE,interviewer_id UUID REFERENCES ugaforce_hr_employees(id),summary TEXT,rehire_eligible BOOLEAN,completed_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS ugaforce_hr_security_events(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),actor_id UUID REFERENCES ugaforce_hr_employees(id),event_type TEXT NOT NULL,severity TEXT NOT NULL DEFAULT 'info',resource TEXT,allowed BOOLEAN,details JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_hr_security_events ON ugaforce_hr_security_events(created_at DESC,severity);
INSERT INTO ugaforce_hr_role_permissions(role_id,resource,can_view,can_edit,scope) SELECT r.id,x.resource,x.v,x.e,x.s FROM ugaforce_hr_roles r JOIN (VALUES ('EMPLOYEE','notifications',true,true,'self'),('HR_SPECIALIST','offboarding',true,true,'all'),('HR_MANAGER','offboarding',true,true,'all'),('HR_ADMIN','offboarding',true,true,'all'),('HR_ADMIN','security',true,true,'all')) x(role_name,resource,v,e,s) ON r.name=x.role_name ON CONFLICT(role_id,resource) DO UPDATE SET can_view=excluded.can_view,can_edit=excluded.can_edit,scope=excluded.scope;