(function(){
'use strict';
const $=id=>document.getElementById(id);
const state={stack:[],current:'main',history:[],commands:{},session:false,user:'',role:'',message:''};
const screens={
main:{id:'V5250-MAIN',title:'VECTOR 5250 MAIN MENU',menu:[['1','Manager Command Center','manager'],['2','Record Search','search'],['3','Recent Transactions','recent'],['4','System Messages','messages'],['5','Help / Prompt','help']]},
manager:{id:'V5250-MGR',title:'MANAGER COMMAND CENTER',menu:[['1','Exception Center','exceptions'],['2','Dispatch Operations','dispatch'],['3','Order Management','orders'],['4','Pickup Management','pickups'],['5','Warehouse Records','warehouse'],['6','Document Center','documents'],['7','Alerts / Tasks','alerts'],['8','Search','search'],['9','Recent Transactions','recent']]},
exceptions:{id:'V5250-EXC',title:'EXCEPTION CENTER',rows:[['1','Critical exceptions requiring manager action','03 OPEN'],['2','Adjustments, releases and overrides awaiting approval','05 PENDING'],['3','Driver exceptions','00 OPEN'],['4','Pickup exceptions','00 OPEN'],['5','Warehouse exceptions','00 OPEN']]},
dispatch:{id:'V5250-DSP',title:'DISPATCH OPERATIONS',rows:[['1','Active driver dispatch board','READY'],['2','Route control','READY'],['3','Delivery movements','READY'],['4','Pickup movements','READY'],['5','Reassignments','READY']]},
orders:{id:'V5250-ORD',title:'ORDER MANAGEMENT',rows:[['1','Active orders','READY'],['2','Delivery orders','READY'],['3','Pickup orders','READY'],['4','Held orders','READY'],['5','Order lookup','READY']]},
pickups:{id:'V5250-PUP',title:'PICKUP MANAGEMENT',rows:[['1','Scheduled pickups','READY'],['2','Driver pickup queue','READY'],['3','Pickup exceptions','READY'],['4','Pickup proof / custody','READY'],['5','Pickup history','READY']]},
warehouse:{id:'V5250-WHR',title:'WAREHOUSE RECORDS',rows:[['1','Receiving records','READY'],['2','Inventory records','READY'],['3','Staging records','READY'],['4','Loading records','READY'],['5','Dispatch records','READY']]},
documents:{id:'V5250-DOC',title:'DOCUMENT CENTER',rows:[['1','Bills of lading','READY'],['2','Delivery documents','READY'],['3','Pickup documents','READY'],['4','Proof of delivery / pickup','READY'],['5','Chain of custody','READY']]},
alerts:{id:'V5250-ALT',title:'ALERTS / TASKS',rows:[['1','Critical alerts','00'],['2','Manager tasks','00'],['3','Approvals awaiting action','00'],['4','System notices','00']]},
search:{id:'V5250-SRC',title:'RECORD SEARCH',custom:'SEARCH'},
recent:{id:'V5250-RCT',title:'RECENT TRANSACTIONS',custom:'RECENT'},
messages:{id:'V5250-MSG',title:'SYSTEM MESSAGES',rows:[['-','No unread system messages',''] ]},
help:{id:'V5250-HLP',title:'COMMAND PROMPT / HELP',rows:[['F3','Back',''],['F4','Prompt / Help',''],['F5','Refresh',''],['F9','Command History',''],['F12','Cancel',''],['F24','More Keys','']]}
};
function menuHtml(menu){return '<div class="menu">'+menu.map(x=>'<button class="btn menuBtn" data-open="'+x[2]+'"><span class="amber">'+x[0]+'</span> '+x[1]+'</button>').join('')+'</div>';}
function rowsHtml(rows){return '<div class="panel">'+rows.map(x=>'<div class="row"><span class="amber">'+x[0]+'</span><span>'+x[1]+'</span><span class="right amber">'+x[2]+'</span></div>').join('')+'</div>';}
function render(name,push){const s=screens[name]||screens.main;if(push&&state.current!==name)state.stack.push(state.current);state.current=name;$('screenName').textContent=s.id+'  '+s.title;if(s.menu)$('content').innerHTML=menuHtml(s.menu);else if(s.custom==='SEARCH')$('content').innerHTML='<div class="panel"><div class="title">SEARCH VECTOR RECORDS</div><div>Enter record reference, U-Code or alias at COMMAND ==&gt;</div><div class="muted" style="margin-top:8px">Search stays inside Vector 5250 and returns terminal result screens.</div></div>';else if(s.custom==='RECENT')$('content').innerHTML='<div class="panel"><div class="title">RECENT VECTOR TRANSACTIONS</div><div>'+((state.history.length?state.history.slice().reverse().map(x=>'<div class="row"><span class="amber">'+x.time+'</span><span>'+x.command+'</span><span class="right">'+x.screen+'</span></div>').join(''):'<div class="muted">No transactions in this session.</div>'))+'</div></div>';else $('content').innerHTML=rowsHtml(s.rows||[]);$('content').querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>render(b.dataset.open,true));setMsg('');}
function setMsg(t,type){$('msg').textContent=t||'';$('msg').className='msg '+(type||'');}
function log(command){state.history.push({command,screen:screens[state.current].id,time:new Date().toLocaleTimeString()});if(state.history.length>100)state.history.shift();}
async function session(){const code=localStorage.getItem('vector5250-access')||'';if(!code){$('sessionState').textContent='SIGN-ON REQUIRED';return false}try{const r=await fetch('/warehouse/manager/session',{headers:{'x-access-code':code},cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.detail||'ACCESS DENIED');state.session=true;state.commands=d.commands||{};state.role=String(d.role||'manager').toUpperCase();$('sessionState').textContent='SESSION ACTIVE · '+state.role;return true}catch(e){state.session=false;$('sessionState').textContent='ACCESS DENIED';setMsg(e.message,'error');return false}}
const numeric={main:{'1':'manager','2':'search','3':'recent','4':'messages','5':'help'},manager:{'1':'exceptions','2':'dispatch','3':'orders','4':'pickups','5':'warehouse','6':'documents','7':'alerts','8':'search','9':'recent'}};
const targetMap={dashboard:'manager',exceptions:'exceptions',dispatch:'dispatch',orders:'orders',warehouse:'warehouse',documents:'documents',alerts:'alerts',search:'search',recent:'recent',favorites:'manager'};
async function exec(raw){const c=String(raw||'').trim().toUpperCase();if(!c)return;if(!(await session()))return;log(c);if(numeric[state.current]&&numeric[state.current][c]){render(numeric[state.current][c],true);setMsg('SELECTION '+c+' ACCEPTED','ok');clearCmd();return}if(c==='F3'){back();return}if(c==='F4'){render('help',true);return}if(c==='F5'){render(state.current,false);setMsg('SCREEN REFRESHED','ok');return}if(c==='F9'){render('recent',true);return}if(c==='F12'){cancel();return}if(c==='F24'){render('help',true);setMsg('ADDITIONAL FUNCTION KEYS','ok');return}const key=c.replace(/^U\s*/,'U-').replace(/^U--/,'U-');const tx=state.commands[key]||state.commands[c];if(tx&&targetMap[tx.target]){render(targetMap[tx.target],true);setMsg(key+' · '+tx.label,'ok');clearCmd();return}if(state.current==='search'){render('search',false);$('content').innerHTML='<div class="panel"><div class="title">SEARCH RESULT</div><div class="row"><span class="amber">REF</span><span>'+c+'</span><span class="right amber">NO MATCH</span></div></div>';setMsg('SEARCH COMPLETE','ok');clearCmd();return}setMsg('INVALID COMMAND OR SELECTION: '+c,'error');}
function clearCmd(){const i=$('cmd');i.value='';i.focus();}
function back(){if(state.stack.length)render(state.stack.pop(),false);else render('main',false);setMsg('F3 · BACK','');}
function cancel(){clearCmd();setMsg('F12 · CANCELLED','');}
function bind(){document.querySelectorAll('[data-key]').forEach(b=>b.onclick=()=>exec(b.dataset.key));$('enter').onclick=()=>exec($('cmd').value);$('cmd').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();exec(e.currentTarget.value)}else if(['F3','F4','F5','F9','F12'].includes(e.key)){e.preventDefault();exec(e.key)}});}
window.VECTOR5250={render,exec,state};bind();render('main',false);session();
})();
