(function(){
'use strict';
const $=id=>document.getElementById(id), host=$('hostScreen');
const state={signedOn:false,user:'',role:'',current:'login',stack:[],history:[],commands:{}};
const screens={
 main:{code:'MAIN',title:'VECTOR 5250 MAIN MENU',menu:[['1','Manager Command Center','manager'],['2','Record Inquiry','search'],['3','Order Management','orders'],['4','Pickup Management','pickups'],['5','Dispatch Records','dispatch'],['6','Document Records','documents'],['7','Exception Center','exceptions'],['8','Audit / Recent Transactions','recent'],['9','System Messages','messages']]},
 manager:{code:'MGR01',title:'MANAGER COMMAND CENTER',menu:[['1','Exception Center','exceptions'],['2','Dispatch Operations','dispatch'],['3','Order Management','orders'],['4','Pickup Management','pickups'],['5','Warehouse Records','warehouse'],['6','Document Center','documents'],['7','Alerts / Tasks','alerts'],['8','Record Inquiry','search'],['9','Recent Transactions','recent']]},
 exceptions:{code:'EXC01',title:'EXCEPTION CENTER',rows:[['1','Critical exceptions requiring manager action','03 OPEN'],['2','Adjustments, releases and overrides awaiting approval','05 PENDING'],['3','Driver exceptions','00 OPEN'],['4','Pickup exceptions','00 OPEN'],['5','Warehouse exceptions','00 OPEN']]},
 dispatch:{code:'DSP01',title:'DISPATCH RECORDS',rows:[['1','Active driver dispatch board','READY'],['2','Route control','READY'],['3','Delivery movements','READY'],['4','Pickup movements','READY'],['5','Reassignments','READY']]},
 orders:{code:'ORD01',title:'ORDER MANAGEMENT',rows:[['1','Active orders','READY'],['2','Delivery orders','READY'],['3','Pickup orders','READY'],['4','Held orders','READY'],['5','Order inquiry','READY']]},
 pickups:{code:'PUP01',title:'PICKUP MANAGEMENT',rows:[['1','Scheduled pickups','READY'],['2','Driver pickup queue','READY'],['3','Pickup exceptions','READY'],['4','Pickup proof / custody','READY'],['5','Pickup history','READY']]},
 warehouse:{code:'WHR01',title:'WAREHOUSE RECORDS',rows:[['1','Receiving records','READY'],['2','Inventory records','READY'],['3','Staging records','READY'],['4','Loading records','READY'],['5','Dispatch records','READY']]},
 documents:{code:'DOC01',title:'DOCUMENT RECORDS',rows:[['1','Bills of lading','READY'],['2','Delivery documents','READY'],['3','Pickup documents','READY'],['4','Proof of delivery / pickup','READY'],['5','Chain of custody','READY']]},
 alerts:{code:'ALT01',title:'ALERTS / TASKS',rows:[['1','Critical alerts','00'],['2','Manager tasks','00'],['3','Approvals awaiting action','00'],['4','System notices','00']]},
 messages:{code:'MSG01',title:'SYSTEM MESSAGES',rows:[['-','No unread system messages','']]},
 search:{code:'INQ01',title:'RECORD INQUIRY',custom:'search'},recent:{code:'AUD01',title:'AUDIT / RECENT TRANSACTIONS',custom:'recent'}
};
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function tick(){const d=new Date();$('clock').textContent=d.toLocaleDateString('en-US',{month:'2-digit',day:'2-digit',year:'2-digit'})+' '+d.toLocaleTimeString('en-US',{hour12:false});} tick();setInterval(tick,1000);
function setMsg(t,type){$('msg').textContent=t||'';$('msg').className='msg '+(type||'');}
function header(code){$('screenCode').textContent=code;$('headerUser').textContent=state.signedOn?(state.user||state.role||'USER'):'--';}
function keys(){return '<div class="keys"><button class="key" data-key="F3">F3=BACK</button><button class="key" data-key="F4">F4=PROMPT</button><button class="key" data-key="F5">F5=REFRESH</button><button class="key" data-key="F9">F9=HISTORY</button><button class="key" data-key="F12">F12=CANCEL</button><button class="key" data-key="F24">F24=MORE</button></div>';}
function command(){return '<div class="command-area"><div class="commandline"><label>COMMAND ==&gt;</label><input id="cmd" class="hostinput" autocomplete="off" autocapitalize="characters" spellcheck="false"></div></div>'+keys();}
function signon(){state.current='login';header('LOGIN');host.innerHTML='<div class="sign-title center">SIGN ON</div><div class="box"><div class="box-title">VECTOR 5250 RECORD SYSTEM</div><div>SYSTEM . . . . . : VECTOR5250</div><div>SUBSYSTEM . . . : QINTER</div><div>ENVIRONMENT . . : PRODUCTION</div><br><div>ENTER YOUR USER ID AND AUTHORIZATION BELOW.</div></div><div class="fieldrow"><label>USER ID ==&gt;</label><input id="userid" class="hostinput" autocomplete="username" autocapitalize="characters" spellcheck="false"></div><div class="fieldrow"><label>AUTHORIZATION ==&gt;</label><input id="auth" type="password" class="hostinput password" autocomplete="current-password"></div><div class="hint">AUTHORIZED VECTOR PERSONNEL ONLY</div><div class="keys"><button class="key" data-login="1">ENTER=SIGN ON</button><button class="key" data-key="F5">F5=REFRESH</button><button class="key" data-key="F12">F12=CANCEL</button></div>';bind();setTimeout(()=>$('userid')?.focus(),50);}
async function login(){const user=($('userid')?.value||'').trim().toUpperCase(),code=$('auth')?.value||'';if(!user||!code){setMsg('USER ID AND AUTHORIZATION REQUIRED','error');return}setMsg('SIGN-ON IN PROGRESS . . .','');try{const r=await fetch('/warehouse/manager/session',{headers:{'x-access-code':code},cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.detail||'SIGN-ON FAILED');state.signedOn=true;state.user=user;state.role=String(d.role||'USER').toUpperCase();state.commands=d.commands||{};sessionStorage.setItem('vector5250-user',user);sessionStorage.setItem('vector5250-access',code);render('main',false);setMsg('SIGN-ON COMPLETED · '+user,'ok')}catch(e){setMsg('CPF9898  '+e.message,'error');}}
function menuRows(a){return a.map(x=>'<div class="menurow" data-open="'+esc(x[2])+'"><span class="sel">'+esc(x[0])+'</span><span>'+esc(x[1])+'</span><span class="status"></span></div>').join('');}
function recordRows(a){return a.map(x=>'<div class="recordrow"><span class="sel">'+esc(x[0])+'</span><span>'+esc(x[1])+'</span><span class="status">'+esc(x[2])+'</span></div>').join('');}
function render(name,push=true){if(!state.signedOn){signon();return}const s=screens[name]||screens.main;if(push&&state.current!==name&&state.current!=='login')state.stack.push(state.current);state.current=name;header(s.code);let body='<div class="screen-title">'+esc(s.title)+'</div><div class="rule"></div>';if(s.menu)body+=menuRows(s.menu);else if(s.custom==='search')body+='<div class="box">ENTER A RECORD NUMBER, U-CODE OR ALIAS AT COMMAND ==&gt;<br><br>INQUIRY RESULTS REMAIN INSIDE THE VECTOR SESSION.</div>';else if(s.custom==='recent')body+='<div>'+((state.history.length?state.history.slice().reverse().map(x=>'<div class="recordrow"><span class="sel">'+esc(x.time)+'</span><span>'+esc(x.command)+'</span><span class="status">'+esc(x.screen)+'</span></div>').join(''):'<div class="box">NO TRANSACTIONS RECORDED IN THIS SESSION.</div>'))+'</div>';else body+=recordRows(s.rows||[]);host.innerHTML=body+command();bind();setMsg('');setTimeout(()=>$('cmd')?.focus(),20);}
const numeric={main:{1:'manager',2:'search',3:'orders',4:'pickups',5:'dispatch',6:'documents',7:'exceptions',8:'recent',9:'messages'},manager:{1:'exceptions',2:'dispatch',3:'orders',4:'pickups',5:'warehouse',6:'documents',7:'alerts',8:'search',9:'recent'}};
const targetMap={dashboard:'manager',exceptions:'exceptions',dispatch:'dispatch',orders:'orders',warehouse:'warehouse',documents:'documents',alerts:'alerts',search:'search',recent:'recent',favorites:'manager'};
function log(c){state.history.push({command:c,screen:(screens[state.current]?.code||'LOGIN'),time:new Date().toLocaleTimeString('en-US',{hour12:false})});if(state.history.length>100)state.history.shift();}
function back(){if(state.stack.length)render(state.stack.pop(),false);else render('main',false);setMsg('F3 · PREVIOUS SCREEN','');}
function signoff(){state.signedOn=false;state.user='';state.role='';state.stack=[];sessionStorage.removeItem('vector5250-user');sessionStorage.removeItem('vector5250-access');signon();setMsg('SESSION ENDED','');}
function exec(raw){const c=String(raw||'').trim().toUpperCase();if(!c)return;log(c);if(c==='F3'){back();return}if(c==='F4'){setMsg('ENTER MENU SELECTION, U-CODE OR RECORD REFERENCE','ok');return}if(c==='F5'){render(state.current,false);setMsg('SCREEN REFRESHED','ok');return}if(c==='F9'){render('recent',true);return}if(c==='F12'){if($('cmd'))$('cmd').value='';setMsg('REQUEST CANCELLED','');return}if(c==='F24'){setMsg('F3 BACK · F4 PROMPT · F5 REFRESH · F9 HISTORY · F12 CANCEL','ok');return}if(c==='SIGNOFF'||c==='LOGOFF'){signoff();return}if(numeric[state.current]?.[c]){render(numeric[state.current][c],true);return}const key=c.replace(/^U\s*/,'U-').replace(/^U--/,'U-'),tx=state.commands[key]||state.commands[c];if(tx&&targetMap[tx.target]){render(targetMap[tx.target],true);setMsg(key+'  '+tx.label,'ok');return}if(state.current==='search'){host.querySelector('.box').innerHTML='RECORD INQUIRY<br><br>REFERENCE . . . : '+esc(c)+'<br>STATUS . . . . . : NO MATCH';setMsg('INQUIRY COMPLETE','ok');return}setMsg('CPF0001  INVALID COMMAND OR SELECTION: '+c,'error');}
function bind(){host.querySelectorAll('[data-open]').forEach(el=>el.onclick=()=>render(el.dataset.open,true));host.querySelectorAll('[data-key]').forEach(el=>el.onclick=()=>{if(state.current==='login'&&el.dataset.key==='F5')signon();else if(state.current==='login'&&el.dataset.key==='F12')setMsg('SIGN-ON CANCELLED','');else exec(el.dataset.key)});host.querySelectorAll('[data-login]').forEach(el=>el.onclick=login);const cmd=$('cmd');if(cmd)cmd.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();exec(cmd.value);cmd.value=''}});const auth=$('auth');if(auth)auth.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();login()}});const uid=$('userid');if(uid)uid.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();$('auth')?.focus()}});}
window.VECTOR5250={state,render,exec,signoff};
const savedUser=sessionStorage.getItem('vector5250-user'),savedCode=sessionStorage.getItem('vector5250-access');if(savedUser&&savedCode){state.user=savedUser;fetch('/warehouse/manager/session',{headers:{'x-access-code':savedCode},cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw Error();state.signedOn=true;state.role=String(d.role||'USER').toUpperCase();state.commands=d.commands||{};render('main',false)}).catch(signon)}else signon();
})();