(function(){
'use strict';
const $=id=>document.getElementById(id),host=$('hostScreen');
const state={signedOn:false,user:'',role:'',current:'login',stack:[],history:[],commands:{},offset:0,pageSize:10,query:'',record:null,mode:'',more:false};
const screens={
main:{code:'MAIN',title:'VECTOR 5250 MAIN MENU',menu:[['1','Manager Command Center','manager'],['2','Record Inquiry','search'],['3','Order Management','orders'],['4','Pickup Management','pickups'],['5','Dispatch Records','dispatch'],['6','Document Records','documents'],['7','Exception Center','exceptions'],['8','Audit / Recent Transactions','recent'],['9','System Messages','messages']]},
manager:{code:'MGR01',title:'MANAGER COMMAND CENTER',menu:[['1','Exception Center','exceptions'],['2','Dispatch Operations','dispatch'],['3','Order Management','orders'],['4','Pickup Management','pickups'],['5','Warehouse Records','warehouse'],['6','Document Center','documents'],['7','Alerts / Tasks','alerts'],['8','Record Inquiry','search'],['9','Recent Transactions','recent']]},
exceptions:{code:'EXC01',title:'EXCEPTION CENTER',rows:[['1','Critical exceptions requiring manager action','03 OPEN'],['2','Adjustments, releases and overrides awaiting approval','05 PENDING'],['3','Driver exceptions','00 OPEN'],['4','Pickup exceptions','00 OPEN'],['5','Warehouse exceptions','00 OPEN']]},
dispatch:{code:'DSP01',title:'DISPATCH RECORDS',rows:[['1','Active driver dispatch board','READY'],['2','Route control','READY'],['3','Delivery movements','READY'],['4','Pickup movements','READY'],['5','Reassignments','READY']]},
orders:{code:'ORD01',title:'ORDER MANAGEMENT',rows:[['1','Active orders','READY'],['2','Delivery orders','READY'],['3','Pickup orders','READY'],['4','Held orders','READY'],['5','Order inquiry','READY']]},
pickups:{code:'PUP01',title:'PICKUP MANAGEMENT',rows:[['1','Scheduled pickups','READY'],['2','Driver pickup queue','READY'],['3','Pickup exceptions','READY'],['4','Pickup proof / custody','READY'],['5','Pickup history','READY']]},
warehouse:{code:'WHR01',title:'WAREHOUSE RECORDS',rows:[['1','Receiving records','READY'],['2','Inventory records','READY'],['3','Staging records','READY'],['4','Loading records','READY'],['5','Dispatch records','READY']]},
documents:{code:'DOC01',title:'DOCUMENT RECORDS',rows:[['1','Bills of lading','READY'],['2','Delivery documents','READY'],['3','Pickup documents','READY'],['4','Proof of delivery / pickup','READY'],['5','Chain of custody','READY']]},
alerts:{code:'ALT01',title:'ALERTS / TASKS',rows:[['1','Critical alerts','00'],['2','Manager tasks','00'],['3','Approvals awaiting action','00'],['4','System notices','00']]},
messages:{code:'MSG01',title:'SYSTEM MESSAGES',rows:[['-','No unread system messages','']]},search:{code:'INQ01',title:'WORK WITH VECTOR RECORDS',custom:'search'},recent:{code:'AUD01',title:'AUDIT / RECENT TRANSACTIONS',custom:'recent'}
};
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function tick(){const d=new Date();$('clock').textContent=d.toLocaleDateString('en-US',{month:'2-digit',day:'2-digit',year:'2-digit'})+' '+d.toLocaleTimeString('en-US',{hour12:false});}tick();setInterval(tick,1000);
function setMsg(t,type){$('msg').textContent=t||'';$('msg').className='msg '+(type||'');}
function header(code){$('screenCode').textContent=code;$('headerUser').textContent=state.signedOn?(state.user||state.role||'USER'):'--';}
function keys(extra=''){return '<div class="keys">'+extra+'<button class="key" data-key="F3">F3=BACK</button><button class="key" data-key="F4">F4=PROMPT</button><button class="key" data-key="F5">F5=REFRESH</button><button class="key" data-key="F9">F9=HISTORY</button><button class="key" data-key="F12">F12=CANCEL</button><button class="key" data-key="F24">F24=MORE</button></div>';}
function command(extra=''){return '<div class="command-area"><div class="commandline"><label>COMMAND ==&gt;</label><input id="cmd" class="hostinput" autocomplete="off" autocapitalize="characters" spellcheck="false"></div></div>'+keys(extra);}
function apiHeaders(){return {'x-access-code':sessionStorage.getItem('vector5250-access')||'','x-vector-user':state.user||'SYSTEM'};}
function signon(){state.current='login';header('LOGIN');host.innerHTML='<div class="sign-title center">SIGN ON</div><div class="box"><div class="box-title">VECTOR 5250 RECORD SYSTEM</div><div>SYSTEM . . . . . : VECTOR5250</div><div>SUBSYSTEM . . . : QINTER</div><div>ENVIRONMENT . . : PRODUCTION</div><br><div>ENTER YOUR USER ID AND AUTHORIZATION BELOW.</div></div><div class="fieldrow"><label>USER ID ==&gt;</label><input id="userid" class="hostinput" autocomplete="username" autocapitalize="characters"></div><div class="fieldrow"><label>AUTHORIZATION ==&gt;</label><input id="auth" type="password" class="hostinput password" autocomplete="current-password"></div><div class="hint">AUTHORIZED VECTOR PERSONNEL ONLY</div><div class="keys"><button class="key" data-login="1">ENTER=SIGN ON</button><button class="key" data-key="F5">F5=REFRESH</button><button class="key" data-key="F12">F12=CANCEL</button></div>';bind();setTimeout(()=>$('userid')?.focus(),50);}
async function login(){const user=($('userid')?.value||'').trim().toUpperCase(),code=$('auth')?.value||'';if(!user||!code){setMsg('CPF9898  USER ID AND AUTHORIZATION REQUIRED','error');return}setMsg('SIGN-ON IN PROGRESS . . .','');try{const r=await fetch('/warehouse/manager/session',{headers:{'x-access-code':code},cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.detail||'SIGN-ON FAILED');state.signedOn=true;state.user=user;state.role=String(d.role||'USER').toUpperCase();state.commands=d.commands||{};sessionStorage.setItem('vector5250-user',user);sessionStorage.setItem('vector5250-access',code);render('main',false);setMsg('CPC2206  SIGN-ON COMPLETED · '+user,'ok')}catch(e){setMsg('CPF9898  '+e.message,'error');}}
function menuRows(a){return a.map(x=>'<div class="menurow" data-open="'+esc(x[2])+'"><span class="sel">'+esc(x[0])+'</span><span>'+esc(x[1])+'</span><span class="status"></span></div>').join('');}
function recordRows(a){return a.map(x=>'<div class="recordrow"><span class="sel">'+esc(x[0])+'</span><span>'+esc(x[1])+'</span><span class="status">'+esc(x[2])+'</span></div>').join('');}
async function render(name,push=true){if(!state.signedOn){signon();return}const s=screens[name]||screens.main;if(push&&state.current!==name&&state.current!=='login')state.stack.push(state.current);state.current=name;state.mode='';header(s.code);let body='<div class="screen-title">'+esc(s.title)+'</div><div class="rule"></div>';if(s.menu)body+=menuRows(s.menu);else if(s.custom==='search'){host.innerHTML=body+'<div class="box">LOADING VECTOR RECORDS . . .</div>'+command('<button class="key" data-key="F6">F6=CREATE</button><button class="key" data-key="F7">F7=PAGE UP</button><button class="key" data-key="F8">F8=PAGE DOWN</button>');bind();await loadRecords();return}else if(s.custom==='recent')body+='<div>'+((state.history.length?state.history.slice().reverse().map(x=>'<div class="recordrow"><span class="sel">'+esc(x.time)+'</span><span>'+esc(x.command)+'</span><span class="status">'+esc(x.screen)+'</span></div>').join(''):'<div class="box">NO TRANSACTIONS RECORDED IN THIS SESSION.</div>'))+'</div>';else body+=recordRows(s.rows||[]);host.innerHTML=body+command();bind();setMsg('');setTimeout(()=>$('cmd')?.focus(),20);}
async function loadRecords(){header('INQ01');const u='/vector5250/api/records?q='+encodeURIComponent(state.query)+'&limit='+state.pageSize+'&offset='+state.offset;try{const r=await fetch(u,{headers:apiHeaders(),cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.detail||'RECORD INQUIRY FAILED');state.more=!!d.more;let rows=(d.results||[]).map(x=>'<div class="recordrow" style="grid-template-columns:42px 1.2fr .8fr .7fr 2fr"><span><input class="hostinput opt" maxlength="2" data-record="'+esc(x.record_no)+'" style="padding:2px;width:32px"></span><span>'+esc(x.record_no)+'</span><span>'+esc(x.record_type)+'</span><span class="status">'+esc(x.status)+'</span><span>'+esc(x.title)+'</span></div>').join('');if(!rows)rows='<div class="box">NO VECTOR RECORDS FOUND.<br><br>F6=CREATE A NEW VECTOR RECORD.</div>';host.innerHTML='<div class="screen-title">WORK WITH VECTOR RECORDS</div><div class="fieldrow"><label>POSITION TO ==&gt;</label><input id="position" class="hostinput" value="'+esc(state.query)+'"></div><div class="hint">2=CHANGE &nbsp; 5=DISPLAY &nbsp; 8=WORK WITH &nbsp; 12=JOURNAL</div><div class="recordrow" style="grid-template-columns:42px 1.2fr .8fr .7fr 2fr"><span class="status">OPT</span><span class="status">RECORD</span><span class="status">TYPE</span><span class="status">STATUS</span><span class="status">TITLE</span></div>'+rows+'<div class="hint">RECORDS '+(d.count?state.offset+1:0)+'-'+(state.offset+(d.results||[]).length)+' OF '+d.count+(state.more?' &nbsp; MORE...':' &nbsp; BOTTOM')+'</div>'+command('<button class="key" data-key="F6">F6=CREATE</button><button class="key" data-key="F7">F7=PAGE UP</button><button class="key" data-key="F8">F8=PAGE DOWN</button>');bind();bindInquiry();setMsg('');}catch(e){setMsg('CPF9898  '+e.message,'error');}}
function bindInquiry(){const p=$('position');if(p)p.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();state.query=p.value.trim().toUpperCase();state.offset=0;loadRecords()}});host.querySelectorAll('.opt').forEach(i=>i.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();runOption(i.value,i.dataset.record)}}));}
async function runSelected(){const i=[...host.querySelectorAll('.opt')].find(x=>x.value.trim());if(i)return runOption(i.value,i.dataset.record);const p=$('position');if(p&&p.value.trim()!==state.query){state.query=p.value.trim().toUpperCase();state.offset=0;return loadRecords()}setMsg('CPF6801  TYPE OPTION OR POSITION VALUE','error');}
async function runOption(opt,recordNo){opt=String(opt||'').trim();if(!['2','5','8','12'].includes(opt)){setMsg('CPF6802  OPTION '+opt+' NOT VALID','error');return}if(opt==='5')return displayRecord(recordNo,false);if(opt==='2')return changeRecord(recordNo);if(opt==='8')return workWithRecord(recordNo);if(opt==='12')return recordJournal(recordNo);}
async function getRecord(no){const r=await fetch('/vector5250/api/records/'+encodeURIComponent(no),{headers:apiHeaders(),cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.detail||'RECORD NOT FOUND');return d;}
function detailLines(r){return '<div class="box"><div>RECORD NUMBER . . . : '+esc(r.record_no)+'</div><div>RECORD TYPE . . . . : '+esc(r.record_type)+'</div><div>STATUS  . . . . . . : '+esc(r.status)+'</div><div>TITLE . . . . . . . : '+esc(r.title)+'</div><div>LOCATION  . . . . . : '+esc(r.location)+'</div><div>OWNER . . . . . . . : '+esc(r.owner)+'</div><div>REFERENCE . . . . . : '+esc(r.reference)+'</div><div>DETAILS . . . . . . : '+esc(r.details)+'</div><div>LAST UPDATE . . . . : '+new Date(r.updated_at*1000).toLocaleString()+'</div></div>';}
async function displayRecord(no,push=true){try{if(push)state.stack.push('search');state.current='record';state.mode='display';state.record=await getRecord(no);header('DSPRCD');host.innerHTML='<div class="screen-title">DISPLAY VECTOR RECORD</div>'+detailLines(state.record)+command();bind();setMsg('CPC1001  RECORD DISPLAYED','ok')}catch(e){setMsg('CPF9898  '+e.message,'error')}}
async function changeRecord(no){try{const lr=await fetch('/vector5250/api/records/'+encodeURIComponent(no)+'/lock',{method:'POST',headers:apiHeaders()}),ld=await lr.json();if(!lr.ok)throw Error(ld.detail||'LOCK FAILED');state.stack.push('search');state.current='record';state.mode='change';state.record=await getRecord(no);header('CHGRCD');const r=state.record;host.innerHTML='<div class="screen-title">CHANGE VECTOR RECORD</div><div class="fieldrow"><label>RECORD . . . . :</label><span>'+esc(r.record_no)+'</span></div><div class="fieldrow"><label>TITLE  . . . . :</label><input id="rTitle" class="hostinput" value="'+esc(r.title)+'"></div><div class="fieldrow"><label>STATUS . . . . :</label><input id="rStatus" class="hostinput" value="'+esc(r.status)+'"></div><div class="fieldrow"><label>LOCATION . . . :</label><input id="rLocation" class="hostinput" value="'+esc(r.location)+'"></div><div class="fieldrow"><label>OWNER  . . . . :</label><input id="rOwner" class="hostinput" value="'+esc(r.owner)+'"></div><div class="fieldrow"><label>REFERENCE  . . :</label><input id="rReference" class="hostinput" value="'+esc(r.reference)+'"></div><div class="fieldrow"><label>DETAILS  . . . :</label><input id="rDetails" class="hostinput" value="'+esc(r.details)+'"></div><div class="hint">RECORD LOCK HELD BY '+esc(state.user)+' · ENTER=SAVE</div>'+command();bind();setMsg('CPC2191  RECORD LOCK ACQUIRED','ok');$('rTitle')?.focus()}catch(e){setMsg('CPF4131  '+e.message,'error')}}
async function saveChange(){const no=state.record.record_no,p={title:$('rTitle').value,status:$('rStatus').value,location:$('rLocation').value,owner:$('rOwner').value,reference:$('rReference').value,details:$('rDetails').value};try{let r=await fetch('/vector5250/api/records/'+encodeURIComponent(no),{method:'PUT',headers:{...apiHeaders(),'Content-Type':'application/json'},body:JSON.stringify(p)}),d=await r.json();if(!r.ok)throw Error(d.detail||'CHANGE FAILED');await fetch('/vector5250/api/records/'+encodeURIComponent(no)+'/lock',{method:'DELETE',headers:apiHeaders()});state.record=d;state.mode='display';header('DSPRCD');host.innerHTML='<div class="screen-title">DISPLAY VECTOR RECORD</div>'+detailLines(d)+command();bind();setMsg('CPC1002  RECORD '+no+' CHANGED','ok')}catch(e){setMsg('CPF9898  '+e.message,'error')}}
async function workWithRecord(no){try{state.stack.push('search');state.current='record';state.mode='work';state.record=await getRecord(no);header('WRKRCD');host.innerHTML='<div class="screen-title">WORK WITH VECTOR RECORD</div>'+detailLines(state.record)+'<div class="hint">2=CHANGE &nbsp; 5=DISPLAY &nbsp; 12=JOURNAL &nbsp; 14=LOCK</div>'+command();bind();setMsg('TYPE OPTION AT COMMAND ==&gt;','ok')}catch(e){setMsg('CPF9898  '+e.message,'error')}}
async function recordJournal(no){try{state.stack.push('search');state.current='journal';state.mode='journal';state.record={record_no:no};header('JRN01');const r=await fetch('/vector5250/api/journal?record_no='+encodeURIComponent(no)+'&limit=50',{headers:apiHeaders(),cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.detail||'JOURNAL FAILED');let rows=(d.results||[]).map(x=>'<div class="recordrow"><span class="sel">'+new Date(x.created_at*1000).toLocaleTimeString()+'</span><span>'+esc(x.action)+' · '+esc(x.user_id)+' · '+esc(x.detail)+'</span><span class="status">'+esc(x.screen_id)+'</span></div>').join('')||'<div class="box">NO JOURNAL ENTRIES FOR '+esc(no)+'</div>';host.innerHTML='<div class="screen-title">VECTOR RECORD JOURNAL · '+esc(no)+'</div>'+rows+command();bind();}catch(e){setMsg('CPF9898  '+e.message,'error')}}
function createRecordScreen(){state.stack.push(state.current);state.current='create';state.mode='create';header('CRTRCD');host.innerHTML='<div class="screen-title">CREATE VECTOR RECORD</div><div class="fieldrow"><label>RECORD TYPE ==&gt;</label><input id="cType" class="hostinput" value="GENERAL"></div><div class="fieldrow"><label>RECORD NO . ==&gt;</label><input id="cNo" class="hostinput" placeholder="BLANK = SYSTEM ASSIGNED"></div><div class="fieldrow"><label>TITLE . . . ==&gt;</label><input id="cTitle" class="hostinput"></div><div class="fieldrow"><label>STATUS  . . ==&gt;</label><input id="cStatus" class="hostinput" value="ACTIVE"></div><div class="fieldrow"><label>REFERENCE . ==&gt;</label><input id="cRef" class="hostinput"></div><div class="fieldrow"><label>DETAILS . . ==&gt;</label><input id="cDetails" class="hostinput"></div><div class="hint">ENTER=CREATE RECORD</div>'+command();bind();$('cType')?.focus();}
async function createRecord(){const p={record_type:$('cType').value,record_no:$('cNo').value,title:$('cTitle').value,status:$('cStatus').value,reference:$('cRef').value,details:$('cDetails').value};try{const r=await fetch('/vector5250/api/records',{method:'POST',headers:{...apiHeaders(),'Content-Type':'application/json'},body:JSON.stringify(p)}),d=await r.json();if(!r.ok)throw Error(d.detail||'CREATE FAILED');state.current='record';state.mode='display';state.record=d;header('DSPRCD');host.innerHTML='<div class="screen-title">DISPLAY VECTOR RECORD</div>'+detailLines(d)+command();bind();setMsg('CPC1003  RECORD '+d.record_no+' CREATED','ok')}catch(e){setMsg('CPF9898  '+e.message,'error')}}
const numeric={main:{1:'manager',2:'search',3:'orders',4:'pickups',5:'dispatch',6:'documents',7:'exceptions',8:'recent',9:'messages'},manager:{1:'exceptions',2:'dispatch',3:'orders',4:'pickups',5:'warehouse',6:'documents',7:'alerts',8:'search',9:'recent'}};
const targetMap={dashboard:'manager',exceptions:'exceptions',dispatch:'dispatch',orders:'orders',warehouse:'warehouse',documents:'documents',alerts:'alerts',search:'search',recent:'recent',favorites:'manager'};
function log(c){state.history.push({command:c,screen:(screens[state.current]?.code||state.current.toUpperCase()),time:new Date().toLocaleTimeString('en-US',{hour12:false})});if(state.history.length>100)state.history.shift();}
async function back(){if(state.mode==='change'&&state.record)await fetch('/vector5250/api/records/'+encodeURIComponent(state.record.record_no)+'/lock',{method:'DELETE',headers:apiHeaders()}).catch(()=>{});if(state.stack.length){const p=state.stack.pop();if(p==='search'){state.current='search';state.mode='';header('INQ01');await loadRecords()}else render(p,false)}else render('main',false);setMsg('F3 · PREVIOUS SCREEN','');}
function signoff(){state.signedOn=false;state.user='';state.role='';state.stack=[];sessionStorage.removeItem('vector5250-user');sessionStorage.removeItem('vector5250-access');signon();setMsg('SESSION ENDED','');}
async function exec(raw){const c=String(raw||'').trim().toUpperCase();if(!c)return;log(c);if(state.mode==='change'&&(c==='ENTER'||c==='SAVE'))return saveChange();if(state.mode==='create'&&(c==='ENTER'||c==='SAVE'))return createRecord();if(c==='F3')return back();if(c==='F4'){setMsg('OPTIONS: 2=CHANGE 5=DISPLAY 8=WORK WITH 12=JOURNAL · COMMANDS: SIGNOFF','ok');return}if(c==='F5'){if(state.current==='search')return loadRecords();if(state.current==='record'&&state.record)return displayRecord(state.record.record_no,false);return render(state.current,false)}if(c==='F6'&&state.current==='search')return createRecordScreen();if(c==='F7'&&state.current==='search'){state.offset=Math.max(0,state.offset-state.pageSize);return loadRecords()}if(c==='F8'&&state.current==='search'){if(state.more)state.offset+=state.pageSize;else setMsg('CPF5026  BOTTOM OF LIST','');return loadRecords()}if(c==='F9')return render('recent',true);if(c==='F12'){if(state.mode==='change')return back();if($('cmd'))$('cmd').value='';setMsg('REQUEST CANCELLED','');return}if(c==='F24'){setMsg('F6 CREATE · F7 PAGE UP · F8 PAGE DOWN · F9 HISTORY · SIGNOFF','ok');return}if(c==='SIGNOFF'||c==='LOGOFF')return signoff();if(state.current==='search'&&/^\d+$/.test(c))return runSelected();if(state.mode==='work'&&state.record){if(c==='2')return changeRecord(state.record.record_no);if(c==='5')return displayRecord(state.record.record_no,false);if(c==='12')return recordJournal(state.record.record_no);if(c==='14'){const r=await fetch('/vector5250/api/records/'+encodeURIComponent(state.record.record_no)+'/lock',{method:'POST',headers:apiHeaders()}),d=await r.json();setMsg(r.ok?'CPC2191  RECORD LOCKED':'CPF4131  '+(d.detail||'LOCK FAILED'),r.ok?'ok':'error');return}}if(numeric[state.current]?.[c])return render(numeric[state.current][c],true);const key=c.replace(/^U\s*/,'U-').replace(/^U--/,'U-'),tx=state.commands[key]||state.commands[c];if(tx&&targetMap[tx.target]){await render(targetMap[tx.target],true);setMsg(key+'  '+tx.label,'ok');return}if(state.current==='search'){state.query=c;state.offset=0;return loadRecords()}setMsg('CPF0001  INVALID COMMAND OR SELECTION: '+c,'error');}
function bind(){host.querySelectorAll('[data-open]').forEach(el=>el.onclick=()=>render(el.dataset.open,true));host.querySelectorAll('[data-key]').forEach(el=>el.onclick=()=>{const k=el.dataset.key;if(state.current==='login'&&k==='F5')signon();else if(state.current==='login'&&k==='F12')setMsg('SIGN-ON CANCELLED','');else exec(k)});host.querySelectorAll('[data-login]').forEach(el=>el.onclick=login);const cmd=$('cmd');if(cmd)cmd.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();if(state.mode==='change')saveChange();else if(state.mode==='create')createRecord();else if(state.current==='search')runSelected();else{exec(cmd.value);cmd.value=''}}else if(['F3','F4','F5','F6','F7','F8','F9','F12'].includes(e.key)){e.preventDefault();exec(e.key)}});const auth=$('auth');if(auth)auth.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();login()}});const uid=$('userid');if(uid)uid.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();$('auth')?.focus()}});}
window.VECTOR5250={state,render,exec,signoff};const su=sessionStorage.getItem('vector5250-user'),sc=sessionStorage.getItem('vector5250-access');if(su&&sc){state.user=su;fetch('/warehouse/manager/session',{headers:{'x-access-code':sc},cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw Error();state.signedOn=true;state.role=String(d.role||'USER').toUpperCase();state.commands=d.commands||{};render('main',false)}).catch(signon)}else signon();
})();