(function(){
'use strict';
const core=()=>window.VECTOR5250,$=id=>document.getElementById(id),host=()=>document.getElementById('hostScreen');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const headers=()=>({'x-access-code':sessionStorage.getItem('vector5250-access')||'','x-vector-user':core()?.state?.user||'SYSTEM'});
let previous='main';
function setHeader(x){if($('screenCode'))$('screenCode').textContent=x}
function setMsg(t,type=''){const e=$('msg');if(e){e.textContent=t||'';e.className='msg '+type}}
function cmdline(){return '<div class="command-area"><div class="commandline"><label>COMMAND ==&gt;</label><input id="cmd" class="hostinput"></div></div><div class="keys"><button class="key" data-vq="F3">F3=BACK</button><button class="key" data-vq="F5">F5=REFRESH</button><button class="key" data-vq="F12">F12=CANCEL</button></div>'}
function begin(name){const c=core();if(!c?.state?.signedOn)return false;previous=c.state.current||'main';c.state.current=name;return true}
function leave(){const c=core();if(c){c.state.current=previous;c.render(previous,false)}}
function bind(refresh){host().querySelectorAll('[data-vq]').forEach(b=>b.onclick=()=>{const k=b.dataset.vq;if(k==='F3')leave();else if(k==='F5')refresh();else setMsg('REQUEST CANCELLED','')});const i=$('cmd');if(i)i.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();const v=i.value.trim().toUpperCase();i.value='';if(['F3','BACK'].includes(v))leave();else if(['F5','REFRESH'].includes(v))refresh();else if(['WRKJOBQ','JOBQ','U-9930'].includes(v))showJobQueues(false);else if(['WRKOUTQ','OUTQ','U-9940'].includes(v))showOutQueues(false);else if(['WRKSPLF','SPLF','U-9950'].includes(v))showSpool(false);else setMsg('CPF0001  INVALID COMMAND OR SELECTION: '+v,'error')}})}
async function showJobQueues(push=true){if(push&&!begin('jobq'))return;else if(!push&&core())core().state.current='jobq';setHeader('WRKJOBQ');host().innerHTML='<div class="screen-title">WORK WITH JOB QUEUES</div><div class="box">LOADING JOB QUEUES . . .</div>'+cmdline();bind(()=>showJobQueues(false));try{const r=await fetch('/vector5250/api/job-queues',{headers:headers(),cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.detail||'JOB QUEUE INQUIRY FAILED');const rows=(d.queues||[]).map(q=>'<div class="recordrow" style="grid-template-columns:40px 1fr .8fr .8fr .8fr"><span><input class="hostinput qopt" maxlength="1" data-q="'+esc(q.queue_name)+'" style="width:30px;padding:2px"></span><span>'+esc(q.queue_name)+'</span><span class="status">'+esc(q.status)+'</span><span>'+esc(q.queued)+'</span><span>'+esc(q.held)+'</span></div>').join('');host().innerHTML='<div class="screen-title">WORK WITH JOB QUEUES</div><div class="hint">5=WORK WITH JOBS</div><div class="recordrow" style="grid-template-columns:40px 1fr .8fr .8fr .8fr"><span>OPT</span><span>JOB QUEUE</span><span>STATUS</span><span>QUEUED</span><span>HELD</span></div>'+rows+cmdline();bind(()=>showJobQueues(false));host().querySelectorAll('.qopt').forEach(i=>i.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();if(i.value.trim()==='5')showQueueJobs(i.dataset.q);else setMsg('CPF6802  OPTION NOT VALID','error')}}));setMsg('CPC1206  JOB QUEUE INFORMATION RETRIEVED','ok')}catch(e){setMsg('CPF9898  '+e.message,'error')}}
async function showQueueJobs(q){previous='jobq';if(core())core().state.current='jobq_detail';setHeader('DSPJOBQ');try{const r=await fetch('/vector5250/api/job-queues/'+encodeURIComponent(q),{headers:headers(),cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.detail||'JOB QUEUE FAILED');const rows=(d.jobs||[]).map(j=>'<div class="recordrow" style="grid-template-columns:1fr .8fr .7fr .7fr 1.5fr"><span>'+esc(j.job_name)+'</span><span>'+esc(j.user_id)+'</span><span class="status">'+esc(j.status)+'</span><span>'+esc(j.priority)+'</span><span>'+esc(j.function)+'</span></div>').join('')||'<div class="box">NO JOBS ON '+esc(q)+'</div>';host().innerHTML='<div class="screen-title">JOB QUEUE · '+esc(q)+'</div><div class="recordrow" style="grid-template-columns:1fr .8fr .7fr .7fr 1.5fr"><span>JOB</span><span>USER</span><span>STATUS</span><span>PTY</span><span>FUNCTION</span></div>'+rows+cmdline();bind(()=>showQueueJobs(q));}catch(e){setMsg('CPF9898  '+e.message,'error')}}
async function showOutQueues(push=true){if(push&&!begin('outq'))return;else if(!push&&core())core().state.current='outq';setHeader('WRKOUTQ');host().innerHTML='<div class="screen-title">WORK WITH OUTPUT QUEUES</div><div class="box">LOADING OUTPUT QUEUES . . .</div>'+cmdline();bind(()=>showOutQueues(false));try{const r=await fetch('/vector5250/api/output-queues',{headers:headers(),cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.detail||'OUTPUT QUEUE INQUIRY FAILED');const rows=(d.queues||[]).map(q=>'<div class="recordrow" style="grid-template-columns:40px 1fr .8fr .8fr .8fr"><span><input class="hostinput oqopt" maxlength="1" data-q="'+esc(q.outq)+'" style="width:30px;padding:2px"></span><span>'+esc(q.outq)+'</span><span class="status">'+esc(q.status)+'</span><span>'+esc(q.files)+'</span><span>'+esc(q.pages)+'</span></div>').join('');host().innerHTML='<div class="screen-title">WORK WITH OUTPUT QUEUES</div><div class="hint">5=WORK WITH SPOOLED FILES</div><div class="recordrow" style="grid-template-columns:40px 1fr .8fr .8fr .8fr"><span>OPT</span><span>OUTQ</span><span>STATUS</span><span>FILES</span><span>PAGES</span></div>'+rows+cmdline();bind(()=>showOutQueues(false));host().querySelectorAll('.oqopt').forEach(i=>i.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();if(i.value.trim()==='5')showSpool(false,i.dataset.q);else setMsg('CPF6802  OPTION NOT VALID','error')}}));setMsg('CPC3312  OUTPUT QUEUE INFORMATION RETRIEVED','ok')}catch(e){setMsg('CPF9898  '+e.message,'error')}}
async function showSpool(push=true,outq=''){if(push&&!begin('splf'))return;else if(!push&&core())core().state.current='splf';setHeader('WRKSPLF');host().innerHTML='<div class="screen-title">WORK WITH SPOOLED FILES</div><div class="box">LOADING SPOOLED FILES . . .</div>'+cmdline();bind(()=>showSpool(false,outq));try{const u='/vector5250/api/spooled-files'+(outq?'?outq='+encodeURIComponent(outq):'');const r=await fetch(u,{headers:headers(),cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.detail||'SPOOLED FILE INQUIRY FAILED');const rows=(d.files||[]).map(f=>'<div class="recordrow" style="grid-template-columns:40px .55fr 1fr .8fr .8fr .7fr .55fr"><span><input class="hostinput sopt" maxlength="1" data-n="'+esc(f.spool_no)+'" style="width:30px;padding:2px"></span><span>'+esc(f.spool_no)+'</span><span>'+esc(f.file_name)+'</span><span>'+esc(f.user_id)+'</span><span>'+esc(f.outq)+'</span><span class="status">'+esc(f.status)+'</span><span>'+esc(f.pages)+'</span></div>').join('')||'<div class="box">NO SPOOLED FILES'+(outq?' ON '+esc(outq):'')+'.</div>';host().innerHTML='<div class="screen-title">WORK WITH SPOOLED FILES'+(outq?' · '+esc(outq):'')+'</div><div class="hint">5=DISPLAY &nbsp; 3=HOLD &nbsp; 6=RELEASE &nbsp; 9=PRINT</div><div class="recordrow" style="grid-template-columns:40px .55fr 1fr .8fr .8fr .7fr .55fr"><span>OPT</span><span>NO</span><span>FILE</span><span>USER</span><span>OUTQ</span><span>STATUS</span><span>PGS</span></div>'+rows+cmdline();bind(()=>showSpool(false,outq));host().querySelectorAll('.sopt').forEach(i=>i.addEventListener('keydown',async e=>{if(e.key==='Enter'){e.preventDefault();const o=i.value.trim(),n=i.dataset.n;if(o==='5')displaySpool(n);else if(['3','6','9'].includes(o)){const map={'3':'HOLD','6':'RELEASE','9':'PRINT'};const rr=await fetch('/vector5250/api/spooled-files/'+n+'/action',{method:'POST',headers:{...headers(),'Content-Type':'application/json'},body:JSON.stringify({action:map[o]})});if(rr.ok)showSpool(false,outq);else setMsg('CPF9898  SPOOLED FILE ACTION FAILED','error')}else setMsg('CPF6802  OPTION NOT VALID','error')}}));setMsg('CPC3394  SPOOLED FILE INFORMATION RETRIEVED','ok')}catch(e){setMsg('CPF9898  '+e.message,'error')}}
async function displaySpool(n){previous='splf';if(core())core().state.current='splf_display';setHeader('DSPSPLF');try{const r=await fetch('/vector5250/api/spooled-files/'+n,{headers:headers(),cache:'no-store'}),f=await r.json();if(!r.ok)throw Error(f.detail||'SPOOLED FILE NOT FOUND');host().innerHTML='<div class="screen-title">DISPLAY SPOOLED FILE</div><div class="box"><div>SPOOL NUMBER . . : '+esc(f.spool_no)+'</div><div>FILE NAME  . . . : '+esc(f.file_name)+'</div><div>JOB . . . . . . : '+esc(f.job_name)+'</div><div>USER  . . . . . : '+esc(f.user_id)+'</div><div>OUTPUT QUEUE . . : '+esc(f.outq)+'</div><div>STATUS  . . . . : '+esc(f.status)+'</div><div>PAGES . . . . . : '+esc(f.pages)+'</div><div>FORM TYPE . . . : '+esc(f.form_type)+'</div></div><div class="box">'+esc(f.content||'NO PRINT DATA')+'</div>'+cmdline();bind(()=>displaySpool(n));}catch(e){setMsg('CPF9898  '+e.message,'error')}}
function capture(e){if(e.key!=='Enter'||e.target?.id!=='cmd')return;const c=String(e.target.value||'').trim().toUpperCase();if(['WRKJOBQ','JOBQ','U-9930'].includes(c)){e.preventDefault();e.stopImmediatePropagation();e.target.value='';showJobQueues(true)}else if(['WRKOUTQ','OUTQ','U-9940'].includes(c)){e.preventDefault();e.stopImmediatePropagation();e.target.value='';showOutQueues(true)}else if(['WRKSPLF','SPLF','U-9950'].includes(c)){e.preventDefault();e.stopImmediatePropagation();e.target.value='';showSpool(true)}}
document.addEventListener('keydown',capture,true);window.VECTOR5250_QUEUES={showJobQueues,showOutQueues,showSpool};
})();