import os,sqlite3,time
from fastapi import APIRouter,Header,Query
from auth import require_permission
DB=os.path.join(os.path.dirname(os.path.abspath(__file__)),'data_hub.db');router=APIRouter()
def db():c=sqlite3.connect(DB);c.row_factory=sqlite3.Row;return c
def one(c,q,a=()):return c.execute(q,a).fetchone()
def pct(a,b):return round((float(a or 0)/float(b or 1))*100,1) if b else 0
@router.get('/warehouse/control-tower')
def tower(warehouse_id:str=Query('main'),days:int=Query(7,ge=1,le=90),x_access_code:str=Header(default='')):
 require_permission(x_access_code,'inventory:read');c=db();now=time.time();since=now-days*86400;today=now-86400
 stock=one(c,'SELECT COUNT(*) skus,COALESCE(SUM(quantity_on_hand),0) units FROM stock WHERE warehouse_id=?',(warehouse_id,));low=one(c,'SELECT COUNT(*) n FROM stock WHERE warehouse_id=? AND quantity_on_hand<=5',(warehouse_id,));lots=one(c,"SELECT COUNT(*) lots,COALESCE(SUM(quantity_available),0) units FROM warehouse_lots WHERE warehouse_id=? AND status='available'",(warehouse_id,));exp=one(c,"SELECT COUNT(*) n,COALESCE(SUM(quantity_available),0) units FROM warehouse_lots WHERE warehouse_id=? AND status='available' AND expiry_date IS NOT NULL AND expiry_date!='' AND date(expiry_date)<=date('now','+30 day')",(warehouse_id,));loc=one(c,'SELECT COUNT(*) total,COALESCE(SUM(capacity),0) capacity,COALESCE(SUM(used_capacity),0) used FROM warehouse_locations WHERE warehouse_id=?',(warehouse_id,))
 orders=one(c,"SELECT COUNT(*) total,SUM(CASE WHEN status='dispatched' THEN 1 ELSE 0 END) dispatched,SUM(CASE WHEN status='partial' THEN 1 ELSE 0 END) partial FROM warehouse_customer_orders WHERE warehouse_id=? AND created_at>=?",(warehouse_id,since));deliver=one(c,"SELECT COUNT(*) total,SUM(CASE WHEN status='delivered' THEN 1 ELSE 0 END) delivered,SUM(CASE WHEN status='failed' THEN 1 ELSE 0 END) failed FROM warehouse_deliveries WHERE warehouse_id=? AND created_at>=?",(warehouse_id,since));tasks=one(c,"SELECT COUNT(*) total,SUM(CASE WHEN status='completed' THEN 1 ELSE 0 END) completed,SUM(CASE WHEN status='blocked' THEN 1 ELSE 0 END) blocked,COALESCE(SUM(CASE WHEN status='completed' THEN quantity ELSE 0 END),0) units FROM warehouse_tasks WHERE warehouse_id=? AND created_at>=?",(warehouse_id,since));staff=one(c,"SELECT COUNT(*) n FROM warehouse_staff WHERE warehouse_id=? AND status='active'",(warehouse_id,));docks=one(c,"SELECT COUNT(*) n FROM warehouse_docks WHERE warehouse_id=?",(warehouse_id,));dock_use=one(c,"SELECT COUNT(DISTINCT dock_id) n FROM warehouse_deliveries WHERE warehouse_id=? AND created_at>=? AND dock_id IS NOT NULL AND dock_id!=''",(warehouse_id,today));ops=[dict(r) for r in c.execute('SELECT operation_type,COUNT(*) count,COALESCE(SUM(quantity),0) quantity FROM warehouse_operations WHERE warehouse_id=? AND created_at>=? GROUP BY operation_type ORDER BY count DESC',(warehouse_id,since)).fetchall()]
 alerts=[]
 if low['n']:alerts.append({'level':'warning','type':'low_stock','message':f"{low['n']} SKUs are at or below low-stock threshold"})
 if exp['n']:alerts.append({'level':'warning','type':'expiry','message':f"{exp['n']} lots / {exp['units']} units expire within 30 days"})
 if tasks['blocked']:alerts.append({'level':'critical','type':'blocked_tasks','message':f"{tasks['blocked']} warehouse tasks are blocked"})
 if deliver['failed']:alerts.append({'level':'critical','type':'delivery_failure','message':f"{deliver['failed']} deliveries failed in the last {days} days"})
 c.close();return {'period_days':days,'inventory':{'skus':stock['skus'],'units':stock['units'],'low_stock_skus':low['n'],'active_lots':lots['lots'],'lot_units':lots['units'],'expiring_lots':exp['n'],'expiring_units':exp['units']},'space':{'locations':loc['total'],'capacity':loc['capacity'],'used':loc['used'],'utilization_pct':pct(loc['used'],loc['capacity'])},'fulfillment':{'orders':orders['total'] or 0,'dispatched':orders['dispatched'] or 0,'partial':orders['partial'] or 0,'dispatch_rate_pct':pct(orders['dispatched'],orders['total']),'deliveries':deliver['total'] or 0,'delivered':deliver['delivered'] or 0,'failed':deliver['failed'] or 0,'delivery_success_pct':pct(deliver['delivered'],deliver['total'])},'labor':{'active_staff':staff['n'],'tasks':tasks['total'] or 0,'completed':tasks['completed'] or 0,'blocked':tasks['blocked'] or 0,'units_handled':tasks['units'] or 0,'completion_rate_pct':pct(tasks['completed'],tasks['total'])},'dock':{'docks':docks['n'],'used_today':dock_use['n'],'utilization_pct':pct(dock_use['n'],docks['n'])},'operations':ops,'alerts':alerts,'generated_at':now}
